name: 'CI setup'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install Dependencies
      run: npm ci
      shell: bash

    - name: Unit tests
      run: npm test
      shell: bash

    - name: Code style
      run: npm run lint
      shell: bash

    - name: Build
      run: npm run build
      shell: bash
