name: Health Check

on:
  push:
    branches:
      - 'feature/**'
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  health_check:
    name: Health check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
